title: Rich Hollis
description: Freelance software guy, Hacker, Code Club volunteer, STEM Ambassador & Dad

meta: I'm Rich Hollis. Freelance full-stack software guy (Web | Mobile | Ruby on Rails | RoR), hacker, Code Club volunteer, STEM Ambassador & Dad from London, UK.

twitter-url: https://twitter.com/richhollis
linkedin-url: http://uk.linkedin.com/in/richhollis2