title: Rich Hollis
description: Freelance full-stack developer, Hacker & Dad

meta: I'm a London based, freelance full-stack software engineer and I love creating and building software products, web applications and sites for people.

twitter-url: https://twitter.com/richhollis
linkedin-url: http://uk.linkedin.com/in/richhollis2