title: Rich Hollis
description: Freelance software guy, Hacker, @CodeClub-er & Dad

meta: I'm Rich Hollis. I'm a freelance full-stack software guy, hacker, @CodeClub-er & Dad from London, UK.

twitter-url: https://twitter.com/richhollis
linkedin-url: http://uk.linkedin.com/in/richhollis2